name: Host Angular app in GitHub 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Building and Deploying...
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_configuration: production 
        base_href: /plac-web-store/ 
        deploy_branch: gh-pages 
        angular_dist_build_folder: dist/placWebStore
